---
apiVersion: v1
kind: Service
metadata:
  name: gateway
spec:
  type: NodePort
  ports:
    - port: 80
      nodePort: 30088
      protocol: TCP
      name: http
      targetPort: 8088
  selector:
    app: gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - env:
          - name: ECHO_TEXT
            valueFrom:
              configMapKeyRef:
                name: gateway-config
                key: vendor
          name: gateway
          image: "docker.io/hashicorp/http-echo"
          args:
            - -listen=:8088
          ports:
            - name: http
              protocol: TCP
              containerPort: 8088
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  vendor: "alipay"